import assert from "node:assert/strict";
import test from "node:test";
import { ADMIN_CSS, ADMIN_HTML, ADMIN_JS } from "../src/admin-assets.js";

test("administrator Mini App separates projects, topic bindings and global settings", () => {
  assert.doesNotThrow(() => new Function(ADMIN_JS));
  assert.match(ADMIN_HTML, /telegram-web-app\.js\?63/);
  assert.match(ADMIN_HTML, /id="createForm"/);
  assert.match(ADMIN_HTML, /id="primaryOwnerId"/);
  assert.match(ADMIN_HTML, /id="topicSearch"/);
  assert.match(ADMIN_HTML, /id="userCount"/);
  assert.match(ADMIN_HTML, /<button id="bindingsTab"[^>]*>Telegram<\/button>/);
  assert.match(ADMIN_HTML, /<h1>Telegram<\/h1>/);
  assert.doesNotMatch(ADMIN_HTML, /Привязки топиков/);
  assert.match(ADMIN_HTML, /один основной рабочий топик/);
  assert.match(ADMIN_HTML, /read-only топиков-наблюдателей/);
  assert.match(ADMIN_HTML, /Доставка наблюдателям/);
  assert.match(ADMIN_HTML, /Настройки SUMMING/);
  assert.match(ADMIN_HTML, /data-admin-section="projects"/);
  assert.match(ADMIN_HTML, /data-admin-section="bindings"/);
  assert.match(ADMIN_HTML, /id="projectsPanel"[^>]+role="tabpanel"/);
  assert.match(ADMIN_HTML, /id="bindingsPanel"[^>]+role="tabpanel"/);
  assert.doesNotMatch(ADMIN_HTML, />Управление<\/button>/);
  assert.match(ADMIN_HTML, /data-admin-section="system"/);
  assert.match(ADMIN_HTML, /data-admin-section="knowledge"/);
  assert.match(ADMIN_HTML, /id="connectorForm"/);
  assert.match(ADMIN_HTML, /id="consentFrom"/);
  assert.match(ADMIN_HTML, /согласие всей группы/i);
  assert.match(ADMIN_HTML, /Пустая дата означает всю доступную историю/);
  assert.match(ADMIN_HTML, /id="sourceSyncForm"/);
  assert.match(ADMIN_HTML, /Перенести Team Space/);
  assert.match(ADMIN_HTML, /id="exportSpace"/);
  assert.match(ADMIN_HTML, /id="exportRecoveryKey"/);
  assert.match(ADMIN_HTML, /id="importRecoveryKey"/);
  assert.match(ADMIN_HTML, /id="onboardingSteps"/);
  assert.match(ADMIN_HTML, /Интерактивный onboarding/);
  assert.match(ADMIN_HTML, /id="systemPanel"[^>]+role="tabpanel"/);
  assert.match(ADMIN_HTML, /Team Memory model egress/);
  assert.match(ADMIN_HTML, /id="modelEgressToggle"/);
  assert.match(ADMIN_HTML, /id="proactiveRepliesToggle"/);
  assert.match(ADMIN_HTML, /Проактивные ответы/);
  assert.match(ADMIN_HTML, /id="modelEgressWeeklyPercent"/);
  assert.match(ADMIN_HTML, /Обновиться сейчас/);
  assert.match(ADMIN_HTML, /id="refreshDeployment"/);
  assert.match(ADMIN_HTML, />Обновить<\/button>/);
  assert.match(ADMIN_HTML, /Каждые 30 минут сервер проверяет/);
  assert.match(ADMIN_HTML, /id="deploymentPhase"/);
  assert.match(ADMIN_HTML, /id="deploymentFailedTests"/);
  assert.match(ADMIN_HTML, /id="deploymentHistory"/);
  assert.match(ADMIN_HTML, /id="nodeRecoveryExportForm"/);
  assert.match(ADMIN_HTML, /id="nodeRecoveryRestoreForm"/);
  assert.match(ADMIN_HTML, /INCLUDE SECRETS/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/recovery\/jobs/);
  assert.match(ADMIN_JS, /data-confirm-recovery/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/projects/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/project-owners/);
  assert.match(ADMIN_JS, /Сделать primary/);
  assert.match(ADMIN_JS, /Добавить owner/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/bindings/);
  assert.match(ADMIN_JS, /data-role/);
  assert.doesNotMatch(ADMIN_JS, /data-portal-key|data-portal-default/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/users/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/deployment/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/deployment\/refresh/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/model-egress/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/model-egress\/proactive-replies/);
  assert.match(ADMIN_JS, /background memory продолжает обновляться/);
  assert.match(ADMIN_JS, /observed_weekly_percent/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/sync/);
  assert.match(ADMIN_JS, /spaceId:\$\("exportSpace"\)\.value/);
  assert.match(ADMIN_JS, /result\.recoveryKey/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/onboarding/);
  assert.match(ADMIN_JS, /renderOnboarding/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/mtproto\/connectors/);
  assert.match(ADMIN_JS, /Подключение к Telegram запущено/);
  assert.doesNotMatch(ADMIN_JS, /Ожидается код Telegram/);
  assert.match(ADMIN_JS, /Не отправлено уведомление о sync/);
  assert.match(ADMIN_JS, /Пропуски по авторам/);
  assert.match(ADMIN_JS, /status\.skippedByAuthor/);
  assert.match(ADMIN_JS, /МЕДИА ОШИБКИ/);
  assert.match(ADMIN_JS, /before-history-boundary/);
  assert.match(ADMIN_JS, /history recovery/);
  assert.match(ADMIN_JS, /восстановление истории запущено/);
  assert.match(ADMIN_JS, /state!=="paused"&&status\.collector\.state!=="failed"/);
  assert.match(ADMIN_JS, /deploymentActive/);
  assert.match(ADMIN_JS, /renderDeploymentFailure/);
  assert.match(ADMIN_JS, /renderDeploymentHistory/);
  assert.match(ADMIN_JS, /activateAdminSection/);
  assert.match(ADMIN_JS, /state\.section==="bindings"/);
  assert.match(ADMIN_JS, /state\.section==="system"/);
  assert.match(ADMIN_JS, /failure\.logTail/);
  assert.match(ADMIN_JS, /deployment-attempt-details/);
  assert.match(ADMIN_JS, /Telegram ID:/);
  assert.match(ADMIN_JS, /Наблюдаемые пользователи топика/);
  assert.match(ADMIN_JS, /Перепривязать топик/);
  assert.match(ADMIN_JS, /method:"DELETE"/);
  assert.match(ADMIN_JS, /Сам Telegram-топик останется в списке/);
  assert.match(ADMIN_CSS, /@media\(max-width:520px\)/);
  assert.match(ADMIN_CSS, /--accent:#ff2e6b/);
  assert.match(ADMIN_CSS, /\.deployment-card/);
  assert.match(ADMIN_CSS, /\.deployment-origin-refresh/);
  assert.match(ADMIN_CSS, /\.model-egress-card/);
  assert.match(ADMIN_CSS, /\.switch input:checked/);
  assert.match(ADMIN_CSS, /\.admin-tabs/);
  assert.match(ADMIN_CSS, /\.admin-panel\.active/);
  assert.match(ADMIN_CSS, /\.owner-manager/);
  assert.match(ADMIN_CSS, /\.onboarding-step/);
  assert.match(ADMIN_CSS, /\.source-sync-card \.sync-counters/);
  assert.match(ADMIN_CSS, /\.skipped-author-grid/);
  assert.match(ADMIN_CSS, /\.unbind-button/);
});
