import assert from "node:assert/strict";
import test from "node:test";
import { ADMIN_CSS, ADMIN_HTML, ADMIN_JS } from "../src/admin-assets.js";

test("administrator Mini App exposes projects, bindings and global settings", () => {
  assert.doesNotThrow(() => new Function(ADMIN_JS));
  assert.match(ADMIN_HTML, /telegram-web-app\.js\?63/);
  assert.match(ADMIN_HTML, /id="createForm"/);
  assert.match(ADMIN_HTML, /id="topicSearch"/);
  assert.match(ADMIN_HTML, /id="userCount"/);
  assert.match(ADMIN_HTML, /Привязки топиков/);
  assert.match(ADMIN_HTML, /Telegram Bot API не отдаёт полный список/);
  assert.match(ADMIN_HTML, /уведомит владельца проекта прямо в выбранном топике/);
  assert.match(ADMIN_HTML, /Настройки SUMMING/);
  assert.match(ADMIN_HTML, /Обновиться сейчас/);
  assert.match(ADMIN_HTML, /id="deploymentPhase"/);
  assert.match(ADMIN_HTML, /id="deploymentFailedTests"/);
  assert.match(ADMIN_HTML, /id="deploymentHistory"/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/projects/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/bindings/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/users/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/deployment/);
  assert.match(ADMIN_JS, /deploymentActive/);
  assert.match(ADMIN_JS, /renderDeploymentFailure/);
  assert.match(ADMIN_JS, /renderDeploymentHistory/);
  assert.match(ADMIN_JS, /failure\.logTail/);
  assert.match(ADMIN_JS, /deployment-attempt-details/);
  assert.match(ADMIN_JS, /Telegram ID:/);
  assert.match(ADMIN_JS, /Наблюдаемые пользователи топика/);
  assert.match(ADMIN_JS, /Перепривязать топик/);
  assert.match(ADMIN_CSS, /@media\(max-width:520px\)/);
  assert.match(ADMIN_CSS, /--accent:#ff2e6b/);
  assert.match(ADMIN_CSS, /\.deployment-card/);
});
