import assert from "node:assert/strict";
import test from "node:test";
import { ADMIN_CSS, ADMIN_HTML, ADMIN_JS } from "../src/admin-assets.js";

test("administrator Mini App exposes projects, bindings and global settings", () => {
  assert.doesNotThrow(() => new Function(ADMIN_JS));
  assert.match(ADMIN_HTML, /telegram-web-app\.js\?63/);
  assert.match(ADMIN_HTML, /id="createForm"/);
  assert.match(ADMIN_HTML, /id="primaryOwnerId"/);
  assert.match(ADMIN_HTML, /id="topicSearch"/);
  assert.match(ADMIN_HTML, /id="userCount"/);
  assert.match(ADMIN_HTML, /Привязки топиков/);
  assert.match(ADMIN_HTML, /Telegram Bot API не отдаёт полный список/);
  assert.match(ADMIN_HTML, /уведомит владельца проекта прямо в выбранном топике/);
  assert.match(ADMIN_HTML, /Настройки SUMMING/);
  assert.match(ADMIN_HTML, /data-admin-section="overview"/);
  assert.match(ADMIN_HTML, /data-admin-section="system"/);
  assert.match(ADMIN_HTML, /data-admin-section="knowledge"/);
  assert.match(ADMIN_HTML, /id="connectorForm"/);
  assert.match(ADMIN_HTML, /id="consentFrom"/);
  assert.match(ADMIN_HTML, /id="sourceSyncForm"/);
  assert.match(ADMIN_HTML, /Перенести Team Space/);
  assert.match(ADMIN_HTML, /id="exportSpace"/);
  assert.match(ADMIN_HTML, /id="exportRecoveryKey"/);
  assert.match(ADMIN_HTML, /id="importRecoveryKey"/);
  assert.match(ADMIN_HTML, /id="onboardingSteps"/);
  assert.match(ADMIN_HTML, /Интерактивный onboarding/);
  assert.match(ADMIN_HTML, /id="systemPanel"[^>]+role="tabpanel"/);
  assert.match(ADMIN_HTML, /Обновиться сейчас/);
  assert.match(ADMIN_HTML, /id="deploymentPhase"/);
  assert.match(ADMIN_HTML, /id="deploymentFailedTests"/);
  assert.match(ADMIN_HTML, /id="deploymentHistory"/);
  assert.match(ADMIN_HTML, /id="nodeRecoveryExportForm"/);
  assert.match(ADMIN_HTML, /id="nodeRecoveryRestoreForm"/);
  assert.match(ADMIN_HTML, /INCLUDE SECRETS/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/recovery\/jobs/);
  assert.match(ADMIN_JS, /data-confirm-recovery/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/projects/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/project-owners/);
  assert.match(ADMIN_JS, /Сделать primary/);
  assert.match(ADMIN_JS, /Добавить owner/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/bindings/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/users/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/deployment/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/sync/);
  assert.match(ADMIN_JS, /spaceId:\$\("exportSpace"\)\.value/);
  assert.match(ADMIN_JS, /result\.recoveryKey/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/onboarding/);
  assert.match(ADMIN_JS, /renderOnboarding/);
  assert.match(ADMIN_JS, /\/api\/viewer\/admin\/mtproto\/connectors/);
  assert.match(ADMIN_JS, /Подключение к Telegram запущено/);
  assert.doesNotMatch(ADMIN_JS, /Ожидается код Telegram/);
  assert.match(ADMIN_JS, /Не отправлено уведомление о sync/);
  assert.match(ADMIN_JS, /state!=="paused"&&status\.collector\.state!=="failed"/);
  assert.match(ADMIN_JS, /deploymentActive/);
  assert.match(ADMIN_JS, /renderDeploymentFailure/);
  assert.match(ADMIN_JS, /renderDeploymentHistory/);
  assert.match(ADMIN_JS, /activateAdminSection/);
  assert.match(ADMIN_JS, /state\.section==="system"/);
  assert.match(ADMIN_JS, /failure\.logTail/);
  assert.match(ADMIN_JS, /deployment-attempt-details/);
  assert.match(ADMIN_JS, /Telegram ID:/);
  assert.match(ADMIN_JS, /Наблюдаемые пользователи топика/);
  assert.match(ADMIN_JS, /Перепривязать топик/);
  assert.match(ADMIN_CSS, /@media\(max-width:520px\)/);
  assert.match(ADMIN_CSS, /--accent:#ff2e6b/);
  assert.match(ADMIN_CSS, /\.deployment-card/);
  assert.match(ADMIN_CSS, /\.admin-tabs/);
  assert.match(ADMIN_CSS, /\.admin-panel\.active/);
  assert.match(ADMIN_CSS, /\.owner-manager/);
  assert.match(ADMIN_CSS, /\.onboarding-step/);
});
